### ISSUE TITLE
Page permettant à un user de s'auto évaluer

### ISSUE THREAD

**Issue by AntoinePollet** [AntoinePollet/hackathon2.0#6]
Voir 
https://excalidraw.com/#room=5bc87ce38eaede6378d7,BjLz8vGTdURix4Pxu5LUzA

**Comment by michael2509** [comment]
**Reminder : Code pour importer des nouveaux users**

const importUsers = async () => {
    console.log('Import en cours...');
    
      const usersData = [
        {
            firstname: 'manager',
            lastname: 'manager',
            birthdate: '1 Janvier 1990',
            hiredate: '8 Mars 2021',
            role: 'manager',
            uuid: '5OmuNBhVwgTbQQp6cUs50sLq42R2',
            skills: [
                {
                    "name": "Capacité du développeur à résoudre des problèmes algorithmiques complexes",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Optimiser les algorithmes existants pour améliorer les performances",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Volonté et capacité du développeur à rester à jour sur les nouvelles technologies",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Bonne pratique de développement",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Développer en permanence ses compétences",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Travail d'équipe",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Partage des idées",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Donner et recevoir des feedbacks de manière constructive",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Communiquer clairement avec des membres non techniques de l'organisation",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Capacité à comprendre et élaborer une architecture technique robuste",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {

                    "name": "Le choix du language importe peu",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Faciliter à s'adapter sur un nouveau projet",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Clean code",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Efficacité",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Capacité à gérer les priorités",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Estimer les délais",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Communiquer efficacement sur l'avancement du projet",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Capacité à écrire des tests unitaires",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Effectuer des tests d'intégration",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Déboguer efficacement les problèmes pour assurer la qualité du code",
                    "category": "Tests et débogage",
                    "rating": 1
                }
            ]
        },
        {
            firstname: 'cto',
            lastname: 'cto',
            birthdate: '1 Janvier 1990',
            hiredate: '8 Mars 2021',
            role: 'cto',
            uuid: 'NlfnmAbD6oO9cTToFzt7zPuf4MY2',
            skills: [
                {
                    "name": "Capacité du développeur à résoudre des problèmes algorithmiques complexes",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Optimiser les algorithmes existants pour améliorer les performances",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Volonté et capacité du développeur à rester à jour sur les nouvelles technologies",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Bonne pratique de développement",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Développer en permanence ses compétences",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Travail d'équipe",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Partage des idées",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Donner et recevoir des feedbacks de manière constructive",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Communiquer clairement avec des membres non techniques de l'organisation",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Capacité à comprendre et élaborer une architecture technique robuste",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {

                    "name": "Le choix du language importe peu",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Faciliter à s'adapter sur un nouveau projet",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Clean code",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Efficacité",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Capacité à gérer les priorités",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Estimer les délais",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Communiquer efficacement sur l'avancement du projet",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Capacité à écrire des tests unitaires",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Effectuer des tests d'intégration",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Déboguer efficacement les problèmes pour assurer la qualité du code",
                    "category": "Tests et débogage",
                    "rating": 1
                }
            ]
        },
        {
            firstname: 'admin',
            lastname: 'admin',
            birthdate: '1 Janvier 1990',
            hiredate: '8 Mars 2021',
            role: 'admin',
            uuid: 'LWsiztmrCPUbnSJZi4Qmqi43xc03',
            skills: [
                {
                    "name": "Capacité du développeur à résoudre des problèmes algorithmiques complexes",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Optimiser les algorithmes existants pour améliorer les performances",
                    "category": "Résolution de problèmes algorithmiques",
                    "rating": 1
                },
                {
                    "name": "Volonté et capacité du développeur à rester à jour sur les nouvelles technologies",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Bonne pratique de développement",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Développer en permanence ses compétences",
                    "category": "Apprentissage continu",
                    "rating": 1
                },
                {
                    "name": "Travail d'équipe",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Partage des idées",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Donner et recevoir des feedbacks de manière constructive",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Communiquer clairement avec des membres non techniques de l'organisation",
                    "category": "Collaboration et communication",
                    "rating": 1
                },
                {
                    "name": "Capacité à comprendre et élaborer une architecture technique robuste",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {

                    "name": "Le choix du language importe peu",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Faciliter à s'adapter sur un nouveau projet",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Clean code",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Efficacité",
                    "category": "Compétences techniques",
                    "rating": 1
                },
                {
                    "name": "Capacité à gérer les priorités",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Estimer les délais",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Communiquer efficacement sur l'avancement du projet",
                    "category": "Gestion de projet",
                    "rating": 1
                },
                {
                    "name": "Capacité à écrire des tests unitaires",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Effectuer des tests d'intégration",
                    "category": "Tests et débogage",
                    "rating": 1
                },
                {
                    "name": "Déboguer efficacement les problèmes pour assurer la qualité du code",
                    "category": "Tests et débogage",
                    "rating": 1
                }
            ]
        }
      ];

      const usersCollectionRef = collection(firestoreDB, 'users');
      for (const userData of usersData) {
        await addDoc(usersCollectionRef, userData);
      }
      console.log('Import terminé !');
}
